package org.david.rain.cloud.start.pojo;

import com.google.common.base.Objects;
import org.apache.commons.lang3.builder.ToStringBuilder;

public class KoTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ko_task.task_id
     *
     * @mbggenerated
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ko_task.role_id
     *
     * @mbggenerated
     */
    private Short roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ko_task.cp_user_id
     *
     * @mbggenerated
     */
    private Integer cpUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ko_task.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ko_task.created_time
     *
     * @mbggenerated
     */
    private Integer createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ko_task.updated_time
     *
     * @mbggenerated
     */
    private Integer updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ko_task.is_deleted
     *
     * @mbggenerated
     */
    private Short isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ko_task.cp_product_id
     *
     * @mbggenerated
     */
    private Short cpProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ko_task.sponsor_task_id
     *
     * @mbggenerated
     */
    private Integer sponsorTaskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ko_task.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ko_task.task_id
     *
     * @return the value of ko_task.task_id
     *
     * @mbggenerated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ko_task.task_id
     *
     * @param taskId the value for ko_task.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ko_task.role_id
     *
     * @return the value of ko_task.role_id
     *
     * @mbggenerated
     */
    public Short getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ko_task.role_id
     *
     * @param roleId the value for ko_task.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Short roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ko_task.cp_user_id
     *
     * @return the value of ko_task.cp_user_id
     *
     * @mbggenerated
     */
    public Integer getCpUserId() {
        return cpUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ko_task.cp_user_id
     *
     * @param cpUserId the value for ko_task.cp_user_id
     *
     * @mbggenerated
     */
    public void setCpUserId(Integer cpUserId) {
        this.cpUserId = cpUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ko_task.status
     *
     * @return the value of ko_task.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ko_task.status
     *
     * @param status the value for ko_task.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ko_task.created_time
     *
     * @return the value of ko_task.created_time
     *
     * @mbggenerated
     */
    public Integer getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ko_task.created_time
     *
     * @param createdTime the value for ko_task.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Integer createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ko_task.updated_time
     *
     * @return the value of ko_task.updated_time
     *
     * @mbggenerated
     */
    public Integer getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ko_task.updated_time
     *
     * @param updatedTime the value for ko_task.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Integer updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ko_task.is_deleted
     *
     * @return the value of ko_task.is_deleted
     *
     * @mbggenerated
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ko_task.is_deleted
     *
     * @param isDeleted the value for ko_task.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ko_task.cp_product_id
     *
     * @return the value of ko_task.cp_product_id
     *
     * @mbggenerated
     */
    public Short getCpProductId() {
        return cpProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ko_task.cp_product_id
     *
     * @param cpProductId the value for ko_task.cp_product_id
     *
     * @mbggenerated
     */
    public void setCpProductId(Short cpProductId) {
        this.cpProductId = cpProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ko_task.sponsor_task_id
     *
     * @return the value of ko_task.sponsor_task_id
     *
     * @mbggenerated
     */
    public Integer getSponsorTaskId() {
        return sponsorTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ko_task.sponsor_task_id
     *
     * @param sponsorTaskId the value for ko_task.sponsor_task_id
     *
     * @mbggenerated
     */
    public void setSponsorTaskId(Integer sponsorTaskId) {
        this.sponsorTaskId = sponsorTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ko_task.remark
     *
     * @return the value of ko_task.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ko_task.remark
     *
     * @param remark the value for ko_task.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }
}