package org.david.rain.boot.start.dao.mapper.oracle;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.david.rain.boot.start.pojo.KoTask;

import java.util.Map;

/**
 * @author xdw9486
 */
@Mapper
public interface PayFundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_task
     *
     * @mbggenerated
     */
    int insert(KoTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_task
     *
     * @mbggenerated
     */
    int insertSelective(KoTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_task
     *
     * @mbggenerated
     */
    KoTask selectByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KoTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(KoTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KoTask record);

    /**
     * 按基金code查找产品
     *
     * @param fundcode 基金code
     * @return
     */
    @Select("SELECT p.PRODUCT_ID_ productId,p.FUNDCODE_ fundcode  FROM PAY_PRODUCT_SD  p where p.FUNDCODE_ = #{fundcode}")
    Map<String, Object> findByFundcode(@Param("fundcode") String fundcode);

}